
spring:
  datasource:
    url: jdbc:postgresql://${MANAGEMENT_DB_HOST}:${MANAGEMENT_DB_PORT}/${MANAGEMENT_DB}
    password: ${MANAGEMENT_DB_PASSWORD}
    username: ${MANAGEMENT_DB_USER}
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:4300/auth/realms/Management
          jwk-set-uri: http://localhost:4300/auth/realms/Management/protocol/openid-connect
      client:
        registration:
          keycloak:
            client-id: management-api
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:4300/realms/Management
            user-name-attribute: preferred_username

server:
  port: 8092
